Fixes all the test cases and makes healthId reflected automatically after verification
Bahmni-Covid19/openmrs-module-bahmniapps pull request #14
Opened 2021-04-28 11:39 UTC by Mahesh-I

2021-04-29 07:16 UTC, praveenadayanand requested changes

2021-04-29 07:16 UTC, praveenadayanand commented on ui/app/registration/controllers/editPatientController.js
> +                                $scope.showHealthId = false;
Can we rename showHealthId to showVerifyHealthID ?

2021-04-29 07:16 UTC, praveenadayanand commented on ui/app/registration/constants.js
> +    patientIdentifiers: {
I think health-id should me made a configuration that is part of the extension points(extensionpoints param) than as a constant here. this is not really a "configuration". It should go alongside hipurl

2021-04-29 07:22 UTC, swatigogia2020 approved these changes

2021-04-29 07:27 UTC, Mahesh-I commented on ui/app/registration/constants.js
> +    patientIdentifiers: {
Yeah, we could make it configurable in the UI but it will be "Health ID" every time in the database (we are not configuring that)

2021-05-05 10:03 UTC, praveenadayanand approved these changes

2021-05-05 10:03 UTC, merged